<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0-windows;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FakeMessenger</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\Resources\**\*" Link="Resources\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <Compile Remove="UI\WpfUI\**\*" />
    <Page Remove="UI\WpfUI\**\*" />
    <ApplicationDefinition Remove="UI\WpfUI\**\*" />
    <None Remove="UI\WpfUI\**\*" />
    <Content Remove="UI\WpfUI\**\*" />
    <EmbeddedResource Remove="UI\WpfUI\**\*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.1.2" />
  </ItemGroup>

</Project>